### ISSUE TITLE
Add support for building from VS2017

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest#41]
I tried installing just VS2017. It has the ability to install the VS2015 toolchain, so although the IDE is newer, the tools don't have to be.

On a fresh Windows PC.  "./everest check" comes close... it expects to find F# version 4.0, but only version 4.1 is installed by VS2017.  This can be resolved by downloading F# 4.0 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=48179.  It can install after VS2017 without breaking anything.

**Comment by BarryBo** [comment]
F# 4.0 depends on msbuild 14, which also isn't installed (error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.)

Installing the Microsoft Build Tools 2015 from https://www.microsoft.com/en-us/download/details.aspx%3Fid%3D48159 resolves that.

**Comment by BarryBo** [comment]
The logic in the Everest script, for setting VS_BIN, doesn't work for VS2015.  They refactored out the tools from the IDE, with new directory structures. 
- VCToolsInstallDir points to a versioned subdirectory of tools, and bin\HostX64\x64\ contains both cl.exe and ml64.exe.
- VCINSTALLDIR\Auxiliary\Build now contains vcvars.bat and vcvars64.bat.

**Comment by msprotz** [comment]
I think F* works with F# 4.1. Does Vale work with any version of F#? We could just try to detect fsc.exe in the new location.

Does the 2015 version of tools, installed via the 2017 installer, follow the new directory structure or the old directory structure?

**Comment by BarryBo** [comment]
I haven't tried Vale using F# 4.1.

The 2015 tools are in a different directory structure than they were in the original VS 2015 install... the assembler is now in the same directory as the C compiler, instead of being in an amd64 directory.

Switching to VS2017 might be something we decide to do as a coordinated effort across Everest projects (Vale, Kremlin, and hence hacl-star and mitls), to avoid having to support multiple styles of VS install.

**Comment by msprotz** [comment]
Yes, I'd be in favor of switching wholesale. Do you need support for the 2015 toolchain as bundled within VS2017 now?

**Comment by BarryBo** [comment]
I can't think of a reason why we would want to use the 2015 toolchain.  If we stick to 2017, we avoid the hassle of having to dual-target for the two sets of languages (and bugs).  Since our code is all-new, we should target the latest VS tools, to get latest security features and performance.

**Comment by msprotz** [comment]
@BarryBo is this still valid knowing that one project you've been working on requires the VS2015 toolchain?

**Comment by tahina-pro** [comment]
The Docker Windows image (ewerest) is now based on VS2017 and successfully builds, so all of these should work now.

**Comment by msprotz** [comment]
If we have another issue that tracks the creation of a powershell script that fetches and installs VS2017, the right version of python, along with "making the ewerest docker file use that powershell script as a first step", then this one can be closed.

**Comment by tahina-pro** [comment]
Issue #4 already tracks most of those: VS 2017
Specifically for switching to Python 3.5, I opened issue #54

**Comment by CarolineMathieson** [comment]
Guys, Python 3.x is not a good idea as most developer tools assume the 2.x version, including scons.

The API, libs etc are very different between the two versions and even in the industry, Python 3.x has not been popular.

Caroline

**Comment by BarryBo** [comment]
Caroline, Vale, the one user of scons in our build at present, is already building with Scons 3 and Python 3.  Awkwardly, the build machine may still be using Scons 2 / python 2.7, which puts us at risk of build breaks that happen on the build machine but not on our dev machines.  Everest is standardizing on Python 3.

**Comment by tahina-pro** [comment]
Vale is now included as a binary release (`./everest get-vale`) rather from its sources, and the F# build of the F* standard library is now done via the `dotnet` command from .NET SDK 6.0, which `./everest check` now checks and installs on Windows (since 0604e7edcd48b21885cf109b090463e03caef54b). So, a full Visual Studio is no longer needed to build Everest on Windows.
Moreover, cc8cda79d3318a024d223b12fe9958df208b334a added a PowerShell script file, `windows-init.ps1`, to install Cygwin and run `./everest check` on Windows. (This script also installs GitHub Actions, since it is primarily meant for CI purposes.)
